[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Eliminamos el ruido de los tests de las librer√≠as
test = "test"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
